=== anaofind/idm_tp_uno/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "nb_joueurs": {
      "type": "integer"
    },
    "variantes": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "participant": {
      "type": "string"
    },
    "regles": {
      "type": "object",
      "properties": {
        "crier_uno": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "remarquer_erreur_uno": {
              "type": "object",
              "properties": {
                "joueur": {
                  "type": "string"
                },
                "actions": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                }
              },
              "required": [
                "joueur",
                "actions"
              ]
            }
          },
          "required": [
            "joueur",
            "remarquer_erreur_uno"
          ]
        },
        "poser_question": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "joueur",
            "actions"
          ]
        },
        "jouer_carte_base": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "choix": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "joueur",
            "choix"
          ]
        },
        "jouer_carte_joker": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "choix": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "joueur",
            "choix"
          ]
        },
        "jouer_carte_plus_2": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "joueur",
            "actions"
          ]
        },
        "jouer_carte_plus_4": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "joueur",
            "actions"
          ]
        },
        "jouer_carte_inversement_sens": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "joueur",
            "actions"
          ]
        },
        "jouer_carte_passe_ton_tour": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "joueur",
            "actions"
          ]
        },
        "jouer_plusieurs_cartes_identiques": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "joueur",
            "actions"
          ]
        },
        "jouer_carte_zero": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "joueur",
            "actions"
          ]
        },
        "jouer_suites_de_cartes": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "actions": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "joueur",
            "actions"
          ]
        },
        "fin_manche": {
          "type": "object",
          "properties": {
            "joueur": {
              "type": "string"
            },
            "nb_cartes": {
              "type": "integer"
            }
          },
          "required": [
            "joueur",
            "nb_cartes"
          ]
        },
        "fin_partie": {
          "type": "object",
          "properties": {
            "participant": {
              "type": "string"
            },
            "nb_points_min": {
              "type": "integer"
            },
            "gagant": {
              "type": "string"
            }
          },
          "required": [
            "participant",
            "nb_points_min",
            "gagant"
          ]
        }
      },
      "required": [
        "crier_uno",
        "poser_question",
        "jouer_carte_base",
        "jouer_carte_joker",
        "jouer_carte_plus_2",
        "jouer_carte_plus_4",
        "jouer_carte_inversement_sens",
        "jouer_carte_passe_ton_tour",
        "jouer_plusieurs_cartes_identiques",
        "jouer_carte_zero",
        "jouer_suites_de_cartes",
        "fin_manche",
        "fin_partie"
      ]
    }
  },
  "required": [
    "nb_joueurs",
    "variantes",
    "participant",
    "regles"
  ]
}

=== anaofind/idm_tp_uno/exemple.json
{
  "nb_joueurs": 2,
  "variantes": [
    "base",
    "equipe"
  ],
  "participant": "equipe",
  "regles": {
    "crier_uno": {
      "joueur": "joueur_existe",
      "remarquer_erreur_uno": {
        "joueur": "joueur_courrant",
        "actions": [
          "piocher_2_cartes"
        ]
      }
    },
    "poser_question": {
      "joueur": "joueur_courrant",
      "actions": [
        "piocher_2_cartes"
      ]
    },
    "jouer_carte_base": {
      "joueur": "joueur_courrant",
      "choix": [
        "meme_couleur",
        "meme_numero",
        "meme_symbole"
      ]
    },

    "jouer_carte_joker": {
      "joueur": "joueur_courrant",
      "choix": [
        "choisir_couleur",
        "changer_couler"
      ]
    },
    "jouer_carte_plus_2": {
      "joueur": "joueur_suivant",
      "actions": [
        "piocher_2_cartes"
      ]
    },
    "jouer_carte_plus_4": {
      "joueur": "joueur_suivant",
      "actions": [
        "piocher_4_cartes"
      ]
    },
    "jouer_carte_inversement_sens": {
      "joueur": "joueur_courrant",
      "actions": [
        "inverser_sens"
      ]
    },
    "jouer_carte_passe_ton_tour": {
      "joueur": "joueur_suivant",
      "actions": [
        "passer_son_tour"
      ]
    },
    "jouer_plusieurs_cartes_identiques": {
      "joueur": "none",
      "actions": ["none"]
    },
    "jouer_carte_zero": {
      "joueur": "none",
      "actions": ["none"]
    },
    "jouer_suites_de_cartes": {
      "joueur": "none",
      "actions": ["none"]
    },
    "fin_manche": {
      "joueur": "joueur_existe",
      "nb_cartes": 0
    },
    "fin_partie": {
      "participant": "participant_existe",
      "nb_points_min": 500,
      "gagant" : "participant_min_points"
    }
  }
}
